name: sp_uf
volumes:
  cargo-cache:
  target:
networks:
  sp_uf_network:
    driver: bridge

services:
  url_finder:
    build: 
      context: .
      dockerfile: Dockerfile.local
    container_name: url_finder
    stop_grace_period: 30s
    working_dir: /app
    # run with cargo watch to auto-reload without restarting container
    command: cargo watch --poll -x 'run --bin url_finder'
    environment:
      - LOG_LEVEL=debug
      - DATABASE_URL=${DMOB_DATABASE_URL}
    volumes:
      - .:/app                                      # bind current directory to /app
      - /dev/null:/app/.env                         # do not use .env file
      - cargo-cache:/usr/local/cargo                # own cargo cache
      - target:/app/target                          # own target directory
    ports:
      - "3010:3010"
    networks:
      - sp_uf_network